### ISSUE TITLE
SF2Mix/SFZ3Mix are out of date

### ISSUE THREAD

**Issue by bchan009** [atrac17/Arcade_Offset#13]
There are currently newer versions of SF2Mix/SFZ3Mix.

I'd like to help update the .mra files and keep things current.  Can someone teach me how to generate the .mra files?

Thanks!

**Comment by atrac17** [comment]
I generate patch offsets with an open tool, if you want to contribute check out [ROMMANGLER](https://github.com/originalgrego/RomMangler). MRA's are generated with a proprietary tool and I provide a template to hand jam your own in the readme.

SFZ3 Mix requires an extreme amount of work and is made for emulators. If the author ever patches the object priority properly then I'll update it. It's not worth my time and effort. I'll work on SF2Mix and get it up.
