### ISSUE TITLE
help with Super Street Fighter II X Grand Master Challenge Japan 940311 Free Play Free Play:

### ISSUE THREAD

**Issue by jmodlin210** [atrac17/Arcade_Offset#14]
Can you please help me with Super Street Fighter II X Grand Master Challenge Japan 940311 Free Play Free Play to patch super street fighter ii x grand master challenge japan 940311 free play for the rom ssf2xj on mameui?

**Comment by atrac17** [comment]
I don't do anything with mame, sorry.
