### ISSUE TITLE
Add Super Street Fighter II Turbo: New Legacy Beta .7 

### ISSUE THREAD

**Issue by sean-omny** [atrac17/Arcade_Offset#15]
Add Super Street Fighter II The New Legacy (World 220208) [Beta v0.7]

by bornspd

https://newlegacy.fr/index.html
https://drive.google.com/drive/folders/1UWDv2FBjr4fSVKhcC1-Kzw3Ymc6Zlqrr?usp=sharing

**Comment by atrac17** [comment]
Done.
