### ISSUE TITLE
arcade_offset_update_insecure.sh is redundant

### ISSUE THREAD

**Issue by Locutus73** [atrac17/Arcade_Offset#2]
Hi, I see you recently introduced arcade_offset_update_insecure.sh because `curl -s --cacert /etc/ssl/certs/cacert.pem` doesn’t work in MiSTer systems after running security_fixes.sh.
That’s correct because security_fixes.sh ditches cacert.pem for a more orthodox /etc/ssl/certs/ structure which works correctly with OpenSSL without the need of pointing to a specific pem file; i.e. curl works with https sites without the --cacert option, not needing the --insecure  option. It works just with the plain curl command.
You can consolidate all in the base arcade_offset_update.sh first trying curl without any --cacert or --insecure option; if it returns 0 then it used secure https thanks to the security_fixes.sh script, if it returns 60 (certificate error), then you can rerun curl with the --cacert option.
Something similar to https://github.com/MiSTer-devel/Updater_script_MiSTer/blob/3954c765f2d675f65f9fddb0f5ef90b5ac27625e/update.sh#L63-L85

**Comment by atrac17** [comment]
I'm aware. Thanks.
