### ISSUE TITLE
Transfer repo

### ISSUE THREAD

**Issue by Toryalai1** [atrac17/Arcade_Offset#30]
Hi Atrac
Hope you are and family doing well.
Pramod reached out to me last week and asked me if I would like to pull this repo into jotego org., I did accept. Could you please go ahead and transfer the ownership of this repo to me? Eventually end goal is to push this to jotego org

**Comment by atrac17** [comment]
I've spoken with @jotego and that isn't his intention. You should fork it and have update_all point to your repository. Speak with @theypsilon.


Reference: https://github.com/jotego/jtcores/issues/614

**Comment by Toryalai1** [comment]
Thanks for the quick reply.
Ok then I’ll keep it as a fork
