### ISSUE TITLE
CPS1/Street Fighter 2 Mix: missing dip switch settings

### ISSUE THREAD

**Issue by mrfpga** [atrac17/Arcade_Offset#6]
Some DIP switch settings are missing in the mra for Street Fighter 2 Mix compared to the version released on jotego/jtbin:

```
<dip bits="7" name="Portuguese Win Quotes" ids="On,Off"/>
<dip bits="11" name="Complete Mode" ids="On,Off"/>
<dip bits="12" name="Classic Mode" ids="On,Off"/>
```

https://github.com/jotego/jtbin/blob/master/mra/_alternatives/_Street%20Fighter%20II'%20%20Champion%20Edition/Street%20Fighter%202%20Mix%20(Ver%201.0%20210623).mra

Description what the missing DIP switch settings do:
https://sf2mix.github.io/system.html

**Comment by atrac17** [comment]
Fixed with the following commits. Thanks! It may take the updater 20 minutes to fetch the changes.

https://github.com/atrac17/Arcade_Offset/commit/fcb885407bcfe3a95e0bba8c681e6566f339ac12
https://github.com/atrac17/Arcade_Offset/commit/9feae71a40ac2332f5ac3b748a1ce36edee619a1
